name: release

on:
  push:
    branches:
      - main

env:
  DEPENDENCIES_CACHE: cache-node-modules
  BUILD_ARTIFACTS: dist-artifacts
  REPO: ${{ secrets.REPO }}
  CR_PAT: ${{ secrets.CR_PAT }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  NX_BASE: origin/main~1
  NX_HEAD: origin/main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Version bump
        run: |
          npm run release
          git push --follow-tags
  build:
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        if: ${{ github.event_name }} == 'pull_request'
        shell: bash
        run: npm run nx -- affected --target=test
      - name: Build
        shell: bash
        run: npm run nx -- affected --target=build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACTS }}
          path: dist
  package:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACTS }}
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist
      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Package
        run: npm run nx -- affected --target=package
