name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEPENDENCIES_CACHE: cache-node-modules
  BUILD_ARTIFACTS: dist-artifacts

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} != 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Version
        shell: bash
        run: npm run nx -- affected --base=last-release --target=version
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag last-release
        shell: bash
        run: git tag -f last-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
  build:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test
        if: ${{ github.event_name }} == 'pull_request'
        shell: bash
        run: npm run nx -- affected --base=last-release --target=test
      - name: Build
        if: ${{ github.event_name }} != 'pull_request'
        shell: bash
        run: npm run nx -- affected --base=last-release --target=build
      - name: Upload artifacts
        if: ${{ github.event_name }} != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACTS }}
          path: dist
